#!/usr/bin/env python3

import http.server
import json
import pyfair
import urllib.parse as urlparse
import traceback
import fair
import sys
from functools import lru_cache

class Engine:

    @lru_cache(maxsize=500)
    def distribution(self, model_spec):
        all = {}
        model = fair.load_model(model_spec, all)
        model.calculate_all()
        return fair.distribution_image(all)

    @lru_cache(maxsize=500)
    def exceedence(self, model_spec):
        all = {}
        model = fair.load_model(model_spec, all)
        model.calculate_all()
        return fair.exceedence_image(all)

    @lru_cache(maxsize=500)
    def summary(self, model_spec):
        all = {}
        model = fair.load_model(model_spec, all)
        model.calculate_all()
        summary = fair.summary(model)
        return summary.to_json(indent=4).encode('utf-8'), "application/json"

    @lru_cache(maxsize=500)
    def curves(self, model_spec):
        all = {}
        model = fair.load_model(model_spec, all)
        model.calculate_all()
        curves = fair.curves(model, all)
        return json.dumps(curves, indent=4).encode('utf-8'), "application/json"

    @lru_cache(maxsize=500)
    def loss(self, model_spec):
        all = {}
        model = fair.load_model(model_spec, all)
        model.calculate_all()
        loss = fair.loss(model, all)
        return json.dumps(loss, indent=4).encode('utf-8'), "application/json"

    @lru_cache(maxsize=500)
    def summary(self, model_spec):
        all = {}
        model = fair.load_model(model_spec, all)
        model.calculate_all()
        summary = fair.summary(model, all)
        return json.dumps(summary, indent=4).encode('utf-8'), "application/json"

    @lru_cache(maxsize=500)
    def pdf(self, model_spec):
        all = {}
        model = fair.load_model(model_spec, all)
        model.calculate_all()
        pdf = fair.pdf(model, all)
        return json.dumps(pdf, indent=4).encode('utf-8'), "application/json"

    @lru_cache(maxsize=500)
    def risk(self, model_spec):
        all = {}
        model = fair.load_model(model_spec, all)
        model.calculate_all()
        risk = fair.risk(model, all)
        return json.dumps(risk, indent=4).encode('utf-8'), "application/json"

    @lru_cache(maxsize=500)
    def results(self, model_spec):
        all = {}
        model = fair.load_model(model_spec, all)
        model.calculate_all()

        res = model.export_results()
        # The meta model has results called 'Risk' instead of the
        # overall model's name.
        r = {}
        for k in res:
            if k == "Risk":
                r[model._name] = res[k]
            else:
                r[k] = res[k]

        r = {
            k: r[k].values.tolist()
            for k in r
        }

        r = json.dumps(r, indent=4).encode('utf-8')

        return r, "application/json"

class HashableDict(dict):
    def __hash__(self):
        return hash(json.dumps(self, sort_keys=True))

class Handler(http.server.BaseHTTPRequestHandler):

    def __init__(self, request, client_address, server):
        self.engine = server.engine
        super().__init__(request, client_address, server)

    def invoke(self, report, model):

        # Make model hashable so that we can use LRU cache.
        model = HashableDict(model)

        if report == "exceedence":
            data, type = self.engine.exceedence(model)
        elif report == "distribution":
            data, type = self.engine.distribution(model)
        elif report == "summary":
            data, type = self.engine.summary(model)
        elif report == "curves":
            data, type = self.engine.curves(model)
        elif report == "loss":
            data, type = self.engine.loss(model)
        elif report == "pdf":
            data, type = self.engine.pdf(model)
        elif report == "risk":
            data, type = self.engine.risk(model)
        elif report == "results":
            data, type = self.engine.results(model)
        else:
            raise RuntimeError("Report %s not known" % report)
        
        self.send_response(200)
        self.send_header("Content-Length", len(data))
        self.send_header("Content-Type", type)
        self.end_headers()
        self.wfile.write(data)
        
    def do_GET(self):

        if self.path == '/favicon.ico':
            self.send_response(400)
            self.send_header("Content-Length", 0)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            return

        try:
            components = urlparse.urlparse(self.path)
            params = urlparse.parse_qs(components.query)
            report = params["report"][0]
            model = json.loads(params["model"][0])
            return self.invoke(report, model)

        except Exception as e:
            print(repr(e))

    def do_POST(self):

        try:
            content_length = int(self.headers['Content-Length'])
            data = self.rfile.read(content_length)
            params = json.loads(data)

            return self.invoke(params["report"], params["model"])

        except Exception as e:
            print(repr(e))

class Server(http.server.HTTPServer):
    def __init__(self, addr, handler):
        self.engine = Engine()
        super().__init__(addr, handler)

if len(sys.argv) <= 1:
    port=8080
else:
    port=int(sys.argv[1])

srv = Server(("", port), Handler)
srv.serve_forever()

